server:
  port: 8091

spring:
  application:
    name: MY-EUREKA-CLIENT

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5
    lease-expiratino-duration-in-seconds: 5
    preferIpAddress: true
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}